server:
  contextPath: /oauth2
  port: 8080

spring:
   thymeleaf:
     mode: LEGACYHTML5
     cache: false
   application:
     name: mystory-server-auth2

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8080/oauth2/user
  user:
    name: user
    password: un_passe

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
debug: false
logging:
  level:
   org.springframework.boot.actuate.autoconfigure: INFO